server:
  port: 8001
spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: account # ??id
          uri: lb://account-api # ????
          predicates:
            - Path=/account/** # ???account?????account-api??????