server:
  port: 8001
spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: account # 包含的服务标识
          uri: lb://account-api # 对应网关
          predicates:
            - Path=/account/** #匹配规则